mod courses;
mod exams;
mod login;
mod object_moved;
mod major_scores;
pub use self::courses::COURSES_PAGE;
pub use self::exams::EXAMS_PAGE;
pub use self::login::LOGIN_PAGE;
pub use self::object_moved::OBJECT_MOVED_PAGE;
pub use self::major_scores::MAJOR_SCORES_PAGE;
